### PR TITLE
Add option to list asset by creating new issue

### PR DESCRIPTION
**Pull request by m52go**
[For the new guidelines on new asset listings](https://github.com/bisq-network/proposals/issues/67), which allows requests for new assets to be issues instead of pull requests.

This PR should be merged at the same time as [this one](https://github.com/bisq-network/bisq/pull/2320).

### CODE REVIEW

**Comment by m52go** [comment]
Closing, as both PRs have been merged.

**Comment by m52go** [comment]
This...was never merged. Not sure what I was thinking. 

@ManfredKarrer would you mind taking a look and ACKing if okay?

File: exchange/howto/list-asset.adoc [hunk 1]
```diff
@@ -12,31 +12,43 @@ Also note that Bisq does not implement any technical infrastructure for listed a
...
 
 A Bisq arbitrator must be able to look up transactions in the asset's block explorer by using the receiver's address. In case that is not possible as a result of enhanced privacy features e.g. in Zcash, Monero and CryptoNote coins, a suggested solution needs to be added to the asset listing pull request (e.g. in Zcash we support only transparent addresses not z-addresses; in Monero we require that the user is using a Monero wallet which supports transaction keys to enable 3rd party audits of the transaction which is used in case of a dispute). As such additional cases require additional effort (popup with background info) it will be up to Bisq contributors whether to add a pull request for the popup and translation strings. Of course the code or the popup can be part of the PR as well but a more detailed description is out of scope of this document.
 
+== Method #1: Create an Issue
 
-== Instructions
+If your asset meets the prerequisites listed above, you may open a new issue in the bisq-network/bisq repository using this link:
+
+https://github.com/bisq-network/bisq/issues/new?template=new_asset.md[Create issue to request new asset listing^]
```
[the remark this answers is not in the document]
Comment (m52go) [reply exchange/howto/list-asset.adoc]: It works right now...template is here:

https://github.com/bisq-network/bisq/blob/master/.github/ISSUE_TEMPLATE/new_asset.md
